apiVersion: v1
kind: Service
metadata:
  name: notiflex-api
  namespace: notiflex
spec:
  selector:
    app: notiflex-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP